server:
  url: "sdfs://localhost:6442"
  pass: password
  disable_trust: true
listener:
  download: false
  upload: true
  write: false
  delete: false
  ignore:
  - ".sdfsclitemp/"
gcs:
  credentials: "/home/sam/keys/hybrics-b39620c158ca.json"
  bucket: "ninjasmith24221"
  enabled: false
  base_path: ""
  projectid: "hybrics"
folder:
  base_path: "/home/sam/sync"
  enabled: true